name: Build

on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    env:
      GPR_USER: ${{ github.actor }}
      GPR_KEY: ${{ secrets.GPR_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build robot code
        run: |
          ./gradlew build \
            -Pgpr.user=$GPR_USER \
            -Pgpr.key=$GPR_KEY \
            --refresh-dependencies \
            -x test

      - name: Trigger Test workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: test.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}