name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  Test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    env:
      GPR_USER: ${{ github.actor }}
      GPR_KEY: ${{ secrets.GPR_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run tests
        run: |
          ./gradlew clean test \
            -Pgpr.user=$GPR_USER \
            -Pgpr.key=$GPR_KEY \
            --refresh-dependencies \
            --no-daemon \
            --stacktrace

      - name: Upload test results
        if: always() # ensures this runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/test-results
            build/reports/jacoco