name: Test

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - name: Fail if Build workflow did not succeed
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "Build workflow failed â€” failing Test workflow."
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run tests
        run: |
          ./gradlew clean test \
            -Pgpr.user=$GPR_USER \
            -Pgpr.key=$GPR_KEY \
            --refresh-dependencies \
            --no-daemon \
            --stacktrace

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/test-results
            build/reports/jacoco